/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStyleguideRouteImport } from './routes/_authenticated/styleguide'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedAchatsIndexRouteImport } from './routes/_authenticated/achats/index'
import { Route as AuthenticatedAchatsNouveauRouteImport } from './routes/_authenticated/achats/nouveau'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStyleguideRoute = AuthenticatedStyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchatsIndexRoute =
  AuthenticatedAchatsIndexRouteImport.update({
    id: '/achats/',
    path: '/achats/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAchatsNouveauRoute =
  AuthenticatedAchatsNouveauRouteImport.update({
    id: '/achats/nouveau',
    path: '/achats/nouveau',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/styleguide': typeof AuthenticatedStyleguideRoute
  '/achats/nouveau': typeof AuthenticatedAchatsNouveauRoute
  '/achats/': typeof AuthenticatedAchatsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/styleguide': typeof AuthenticatedStyleguideRoute
  '/': typeof AuthenticatedIndexRoute
  '/achats/nouveau': typeof AuthenticatedAchatsNouveauRoute
  '/achats': typeof AuthenticatedAchatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/styleguide': typeof AuthenticatedStyleguideRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/achats/nouveau': typeof AuthenticatedAchatsNouveauRoute
  '/_authenticated/achats/': typeof AuthenticatedAchatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalogue'
    | '/styleguide'
    | '/achats/nouveau'
    | '/achats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/catalogue'
    | '/styleguide'
    | '/'
    | '/achats/nouveau'
    | '/achats'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/catalogue'
    | '/_authenticated/styleguide'
    | '/_authenticated/'
    | '/_authenticated/achats/nouveau'
    | '/_authenticated/achats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/styleguide': {
      id: '/_authenticated/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof AuthenticatedStyleguideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achats/': {
      id: '/_authenticated/achats/'
      path: '/achats'
      fullPath: '/achats/'
      preLoaderRoute: typeof AuthenticatedAchatsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achats/nouveau': {
      id: '/_authenticated/achats/nouveau'
      path: '/achats/nouveau'
      fullPath: '/achats/nouveau'
      preLoaderRoute: typeof AuthenticatedAchatsNouveauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedStyleguideRoute: typeof AuthenticatedStyleguideRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAchatsNouveauRoute: typeof AuthenticatedAchatsNouveauRoute
  AuthenticatedAchatsIndexRoute: typeof AuthenticatedAchatsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedStyleguideRoute: AuthenticatedStyleguideRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAchatsNouveauRoute: AuthenticatedAchatsNouveauRoute,
  AuthenticatedAchatsIndexRoute: AuthenticatedAchatsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
